name: "Bundlewatch"

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: yarn build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
