on: [push]

name: Quality Check

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    steps:
      - uses: actions/checkout@v3
      - name: Node LTS versions
        uses: msimerson/node-lts-versions@v1.4.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build
      - uses: willcaul/jest-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "yarn jest"
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
